/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PingJNI */

#ifndef _Included_PingJNI
#define _Included_PingJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PingJNI
 * Method:    ping
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_PingJNI_ping
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
