/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNItest_HelloJNI */

#ifndef _Included_JNItest_HelloJNI
#define _Included_JNItest_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNItest_HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNItest_HelloJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
