blank_issues_enabled: true
contact_links:
  - name: Professor Support.
    url: https://thartmanoftheredwoods.github.io/.
    about: The place to search for articles I have written.
  -name: Aidan
    email: aidankai@gmail.com
    about: team lead person/scrum team member
  -name: Adrienne
    email: avansummmern245@mycr.redwoods.edu
    about: team member
  -name: Raymond Valdez
    email: rvaldez216@mycr.redwoods.edu
    about: Team Member