/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_networkscan_cis18_PingDecorator */

#ifndef _Included_com_networkscan_cis18_PingDecorator
#define _Included_com_networkscan_cis18_PingDecorator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_networkscan_cis18_PingDecorator
 * Method:    pingHost
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_networkscan_cis18_PingDecorator_pingHost
  (JNIEnv *, jobject, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
